//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kioskotem.wcfoperadora {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tabla", Namespace="http://schemas.datacontract.org/2004/07/wcfoperadora")]
    [System.SerializableAttribute()]
    public partial class Tabla : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ColumnasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private kioskotem.wcfoperadora.Fila[] FilasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Columnas {
            get {
                return this.ColumnasField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnasField, value) != true)) {
                    this.ColumnasField = value;
                    this.RaisePropertyChanged("Columnas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public kioskotem.wcfoperadora.Fila[] Filas {
            get {
                return this.FilasField;
            }
            set {
                if ((object.ReferenceEquals(this.FilasField, value) != true)) {
                    this.FilasField = value;
                    this.RaisePropertyChanged("Filas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fila", Namespace="http://schemas.datacontract.org/2004/07/wcfoperadora")]
    [System.SerializableAttribute()]
    public partial class Fila : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CamposField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Campos {
            get {
                return this.CamposField;
            }
            set {
                if ((object.ReferenceEquals(this.CamposField, value) != true)) {
                    this.CamposField = value;
                    this.RaisePropertyChanged("Campos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfoperadora.IsvcOperadoraMx")]
    public interface IsvcOperadoraMx {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsvcOperadoraMx/getEjecutaStoredProcedure1", ReplyAction="http://tempuri.org/IsvcOperadoraMx/getEjecutaStoredProcedure1Response")]
        kioskotem.wcfoperadora.Tabla getEjecutaStoredProcedure1(string NombreSP, string Valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsvcOperadoraMx/getEjecutaStoredProcedure", ReplyAction="http://tempuri.org/IsvcOperadoraMx/getEjecutaStoredProcedureResponse")]
        kioskotem.wcfoperadora.Tabla getEjecutaStoredProcedure(string NombreSP, string[] Valores);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsvcOperadoraMxChannel : kioskotem.wcfoperadora.IsvcOperadoraMx, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsvcOperadoraMxClient : System.ServiceModel.ClientBase<kioskotem.wcfoperadora.IsvcOperadoraMx>, kioskotem.wcfoperadora.IsvcOperadoraMx {
        
        public IsvcOperadoraMxClient() {
        }
        
        public IsvcOperadoraMxClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsvcOperadoraMxClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsvcOperadoraMxClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsvcOperadoraMxClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public kioskotem.wcfoperadora.Tabla getEjecutaStoredProcedure1(string NombreSP, string Valores) {
            return base.Channel.getEjecutaStoredProcedure1(NombreSP, Valores);
        }
        
        public kioskotem.wcfoperadora.Tabla getEjecutaStoredProcedure(string NombreSP, string[] Valores) {
            return base.Channel.getEjecutaStoredProcedure(NombreSP, Valores);
        }
    }
}
